### ISSUE TITLE
Request: Past events should still show in dimmed/faded color instead of dimmed/faded grey

### ISSUE THREAD

**Issue by sbbish** [adelespinasse/gcalcolor#10]
A recent change made it so all past events now show in a dimmed or faded grey. Past events used to show in dimmed or faded color (whatever color they were originally assigned). I have color coding on my calendar so I can easily tell at a glance the event type or which shared calendar it is from. I use this color coding for past events too. If I want to look back at a date to see what I had scheduled, it is harder to find specific events when all events are colored grey. Color coding on a calendar is useful not only for future events, but for past events, too.

**Comment by adelespinasse** [comment]
You're right, I'll try to look into this but I can't promise I'll be able to fix it.

**Comment by sbbish** [comment]
Much appreciated. My wife and I both love this extension. It's a must-have extension for both of us.

**Comment by adelespinasse** [comment]
Fixed in #11. The past event colors may be a little lighter than ideal. They were extremely faint until I increased the opacity, which helped; unfortunately the color values it uses for past events are still lighter than future events, and I didn't see an obvious way to tell the difference so that I could darken the past event colors without changing the future events.
